(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'DAL' object has no attribute 'kidcloth'"
p3
sS'layer'
p4
S'/home/pratyusha/web2py/applications/yorock/controllers/kidcloth.py'
p5
sS'code'
p6
S'def index():\n    kidcloth = db(db.kidcloth).select(orderby=db.kidcloth.name)\n    return locals()\n\nresponse._vars=response._caller(index)\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/pratyusha/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/pratyusha/web2py/applications/yorock/controllers/kidcloth.py", line 5, in <module>\n  File "/home/pratyusha/web2py/gluon/globals.py", line 393, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/pratyusha/web2py/applications/yorock/controllers/kidcloth.py", line 2, in index\n    kidcloth = db(db.kidcloth).select(orderby=db.kidcloth.name)\n  File "/home/pratyusha/web2py/gluon/packages/dal/pydal/base.py", line 929, in __getattr__\n    return ogetattr(self, key)\nAttributeError: \'DAL\' object has no attribute \'kidcloth\'\n'
p11
s.